version: "3.4"

services:
  gitlab-runner:
    hostname: local
    image: gitlab-local-runner
    restart: always
    container_name: gitlab-local-runner
    build:
      context: ./
      args:
        - FROM_IMAGE=gitlab/gitlab-runner:latest
    volumes:
      - type: bind
        source: /srv/gitlab-runner/config
        target: /etc/gitlab-runner
      - type: bind
        source: /srv/gitlab-runner-dind
        target: /var/lib/docker
    ports:
      - '9012:9012'
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
##    volumes:
#      # Grant display access to X Server.
##      - type: bind
##        source: /tmp/.X11-unix
##        target: /tmp/.X11-unix
#      # Grant audio access to PulseAudio.
##      - type: bind
##        source: ${XDG_RUNTIME_DIR}/pulse/native
##        target: ${XDG_RUNTIME_DIR}/pulse/native
#      # Init self
##      - type: bind
##        source: ./docker
##        target: /home/docker/docker
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#          external_url 'http://192.168.0.5:12000'
#          gitlab_rails['time_zone'] = 'Asia/Tokyo'
##          gitlab_rails['gitlab_host'] = '127.10.100.10:8080'
##      # Display X Server GUIs.
##      - DISPLAY=${DISPLAY}
##      - QT_X11_NO_MITSHM=1
##      # Configure the Nvidia Docker interface.
##      - NVIDIA_VISIBLE_DEVICES=all
##      - NVIDIA_DRIVER_CAPABILITIES=all
##      - DOCKER_RUNTIME=${DOCKER_RUNTIME}
##      # PulseAudio.
##      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
##      # ID.
##      - HOST_UID=${HOST_UID}
##      - HOST_GID=${HOST_GID}
##      - USER_NAME=${USER_NAME}
##      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}

#version: '3.6'
#services:
#  web:
#    image: 'gitlab/gitlab-ce:latest'
#    restart: always
#    hostname: gitlab-ce
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        external_url 'http://gitlab.example.com'
#        gitlab_rails['gitlab_shell_ssh_port'] = 2224
##        gitlab_rails['initial_root_password'] = "root1234"
#        # Add any other gitlab.rb configuration here, each on its own line
#    ports:
#      - '8929:80'
#      - '2224:22'
#    volumes:
#       - '/srv/gitlab/config:/etc/gitlab'
#       - '/srv/gitlab/logs:/var/log/gitlab'
#       - '/srv/gitlab/data:/var/opt/gitlab'
#    shm_size: '256m'
#

#services:
#  gitlab:
#    hostname: local-gitlab-server
##    image: git-server:20.04
#    image: gitlab/gitlab-ce:latest
#    container_name: gitlab-ce
##    build:
##      context: ./
##      args:
##        - FROM_IMAGE=gitlab/gitlab-ce:latest
##        - FROM_IMAGE=ubuntu:20.04
##        - FROM_IMAGE=nvidia/cudagl:11.3.1-devel-ubuntu20.04
##        - DOCKERFILE_COMMIT_SHORT_SHA
##    volumes:
#      # Grant display access to X Server.
##      - type: bind
##        source: /tmp/.X11-unix
##        target: /tmp/.X11-unix
#      # Grant audio access to PulseAudio.
##      - type: bind
##        source: ${XDG_RUNTIME_DIR}/pulse/native
##        target: ${XDG_RUNTIME_DIR}/pulse/native
#      # Init self
##      - type: bind
##        source: ./docker
##        target: /home/docker/docker
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#          external_url 'http://192.168.0.5:12000'
#          gitlab_rails['time_zone'] = 'Asia/Tokyo'
##          gitlab_rails['gitlab_host'] = '127.10.100.10:8080'
##      # Display X Server GUIs.
##      - DISPLAY=${DISPLAY}
##      - QT_X11_NO_MITSHM=1
##      # Configure the Nvidia Docker interface.
##      - NVIDIA_VISIBLE_DEVICES=all
##      - NVIDIA_DRIVER_CAPABILITIES=all
##      - DOCKER_RUNTIME=${DOCKER_RUNTIME}
##      # PulseAudio.
##      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
##      # ID.
##      - HOST_UID=${HOST_UID}
##      - HOST_GID=${HOST_GID}
##      - USER_NAME=${USER_NAME}
##      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
#    # Use 'network_mode: host' with the real robot or 'network_mode: bridge' for separated networks (multiple independent containers).
#    ports:
#      - '12000:12000'
#      - '2022:22'
##    tty: true
#    #    stdin_open: true
##    privileged: true
##    restart: always
#    #    command: /root/HSR/docker/hsr-devel/scripts/initialize-docker-container.bash
##    deploy:
##      resources:
##        reservations:
##          devices:
##            - capabilities: [gpu]
