version: "3.4"

services:
  gitlab-runner:
    hostname: local
    image: gitlab-local-runner
    restart: always
    container_name: gitlab-local-runner
    build:
      context: ./
      args:
        - FROM_IMAGE=gitlab/gitlab-runner:latest
    volumes:
      - type: bind
        source: /srv/runner/volumes/config
        target: /etc/gitlab-runner
      - type: bind
        source: /srv/runner/docker
        target: /var/lib/docker
#    ports:
#      - '9012:9012'
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
