version: "3.4"

services:
  gitlab-server:
    hostname: gitlab
    image: gitlab-server:20.04
    container_name: gitlab-server
    build:
      context: ./
      args:
        - FROM_IMAGE=ubuntu:20.04
    volumes:
      - type: bind
        source: ./docker
        target: /root/docker
      - type: bind
        source: /srv/gitlab-server/volumes
        target: /srv
      - type: bind
        source: /srv/gitlab-server/docker
        target: /var/lib/docker
    ports:
      - "9010:80"
      - '2224:22'
#    restart: always
    privileged: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    networks:
      fixed_ip:
        ipv4_address: 192.168.20.74

networks:
  fixed_ip:
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
          gateway: 192.168.20.1
